// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewComment struct {
	Content   string  `json:"content"`
	Author    string  `json:"author"`
	CommentID *string `json:"commentId,omitempty"`
	PostID    *string `json:"postId,omitempty"`
}

type NewPost struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	Commentable bool   `json:"commentable"`
	Author      string `json:"author"`
}

type Query struct {
}

type Subscription struct {
}
