FROM golang:1.22.3 AS build-stage

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /poster-app

FROM gcr.io/distroless/base-debian11 AS release-stage

WORKDIR /

COPY --from=build-stage /poster-app /poster-app

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/poster-app"]
